import { TextField } from "@mui/material";
import { Box } from "@mui/system";
import Head from "next/head";
import { Header } from "../components/Header";

export default function Home() {
  return (
    <div style={{ height: "100vh" }}>
      <Head>
        <title>Todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Box sx={{ paddingY: 8, paddingX: 30 }}>
        <TextField
          fullWidth
          id="outlined-basic"
          label="Task"
          variant="outlined"
        />
      </Box>
    </div>
  );
}
