import { Alert, TextField } from "@mui/material";
import { Box } from "@mui/system";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Header } from "../components/Header";

export default function Home() {
  const [tasks, setTasks] = useState([]);
  const endpoint = "http://localhost:9000";

  useEffect(() => {
    fetch(`${endpoint}/api/tasks`)
      .then((res) => res.json())
      .then((data) => setTasks(data));
  }, []);

  console.log(tasks);

  return (
    <div style={{ height: "100vh" }}>
      <Head>
        <title>Todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Box sx={{ paddingY: 8, paddingX: 30 }}>
        <TextField
          fullWidth
          id="outlined-basic"
          label="Task"
          variant="outlined"
        />

        <Box sx={{ paddingY: 8 }}>
          {tasks?.map((doc, i) => (
            <Alert key={i} severity="info">
              {doc.task}
            </Alert>
          ))}
        </Box>
      </Box>
    </div>
  );
}
